# Generated by Django 3.2.7 on 2022-07-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jr_services_app', '0002_auto_20210926_0149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
